version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network
